# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9-jdk-8

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install -y openjfx genisoimage
          - mvn -B -DskipTests -Pinstallers,it.tidalwave-ci-v1,generate-revision-id
