image: maven:3.6.3-openjdk-11

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y genisoimage
          - mvn -B -DskipTests -Pinstallers,it.tidalwave-ci-v1,generate-revision-id
